/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.CategoryAxis;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.XYChart;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.StackPane;
import javax.swing.GroupLayout.Group;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author waruwat
 */
public class HomePanel extends javax.swing.JPanel {

    private int cc = 1;
    private JFXPanel fxPanel;
    ProductMenu obj = new ProductMenu();
    ArrayList<Product> list = obj.getProductList();

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        productMenu1.SetQueryTable("WHERE count <= '20' ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productMenu1 = new swing.ProductMenu();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/welcome.png"))); // NOI18N
        jLabel1.setText("Welcome!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("สินค้าที่ใกล้หมด");

        productMenu1.setBackground(new java.awt.Color(71, 120, 197));

        jButton1.setText("Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(productMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)))
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(274, 274, 274))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
        
        JPanel mainPanel = new JPanel(new BorderLayout());
        fxPanel = new JFXPanel();
        mainPanel.add(fxPanel, BorderLayout.CENTER);
        JButton b1 = new JButton("Change Chart");
        JLabel titleLabel = new JLabel("All Sales");
        titleLabel.setFont(new Font("Courier", Font.BOLD, 30));
        JPanel p = new JPanel(new GridLayout(1, 5));
        p.add(new JLabel(""));
        p.add(new JLabel(""));
        titleLabel.setForeground(Color.white);
        p.setBackground(Color.darkGray);
        p.add(titleLabel);
        p.add(new JLabel(""));
        p.add(b1);
        mainPanel.add(p, BorderLayout.NORTH);
        b1.setBackground(Color.darkGray);
        JFrame framePie = new JFrame();
        framePie.add(mainPanel);
        framePie.setVisible(true);
        framePie.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        titleLabel.setHorizontalAlignment(JLabel.CENTER);
        framePie.setSize(900, 800);
        framePie.setMinimumSize(new Dimension(800, 800));
        ShowChart();
        b1.addActionListener((java.awt.event.ActionEvent evt1) -> {
            cc += 1;
            ShowChart();
            
        });


    }//GEN-LAST:event_jButton1ActionPerformed
    private void ShowChart() {
         
        
        if (cc % 2 == 0) {

                PieChart pieChart = new PieChart();
                for (int i = 0; i < list.size(); i++) {
                    PieChart.Data slice1 = new PieChart.Data(list.get(i).getName(), list.get(i).getCount());
                    pieChart.getData().add(slice1);

                }
                StackPane root = new StackPane(pieChart);
                Scene scene = new Scene(root, 800, 800);
                fxPanel.setScene(scene);
                pieChart.setMinSize(700, 700);
            } else {
                NumberAxis lineYAxis = new NumberAxis(0, 200, 10);
                //lineYAxis.setTickLabelFormatter(new NumberAxis.DefaultFormatter(lineYAxis,"$",null));
                lineYAxis.setLabel("Numbers");
                CategoryAxis lineXAxis = new CategoryAxis();
                lineXAxis.setLabel("Products");
                BarChart barChart
                        = new BarChart<>(lineXAxis, lineYAxis);

                for (int i = 0; i < list.size(); i++) {
                    XYChart.Series<String, Number> series1 = new XYChart.Series<String, Number>();
                    series1.setName(list.get(i).getName());
                    series1.getData().add(new XYChart.Data<String, Number>(list.get(i).getName(), list.get(i).getCount()));
                    barChart.getData().add(series1);
                }

                StackPane root = new StackPane(barChart);
                Scene scene = new Scene(root, 800, 800);
                fxPanel.setScene(scene);
                barChart.setMinSize(700, 700);
            }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private swing.ProductMenu productMenu1;
    // End of variables declaration//GEN-END:variables
}
